version: '3.8'

services:
  edition-manager:
    build: .
    volumes:
      - ./config:/app/config
      - ./metadata_backup:/app/metadata_backup
    environment:
      - TZ=${TZ:-America/Los_Angeles}
      - RUN_MODE=${RUN_MODE:---all}
    restart: unless-stopped
    command: >
      sh -c "if [ ! -f /app/config/config.ini ]; then
              cp /app/config/config.default.ini /app/config/config.ini;
             fi && 
             python edition-manager.py ${RUN_MODE:---all}"
